/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SchoolReceiveRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.SchoolReceiveOrganization;
import Business.Role.SchoolReceiverRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SendToSchoolRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhb970327
 */
public class SchoolReceiveWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SchoolReceiveOrganization schoolreceiveorganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private SendToSchoolRequest sendToSchoolRequest;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form SchoolReceiveWorkAreaJPanel
     */
    public SchoolReceiveWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SchoolReceiveOrganization schoolreceiveorganization, Enterprise enterprise, EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.schoolreceiveorganization = schoolreceiveorganization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) receiveJTable.getModel();
        model.setRowCount(0);

        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = ((SendToSchoolRequest) request).getStatus();
            row[2] = ((SendToSchoolRequest) request).getDistribution() == null ? "" : ((SendToSchoolRequest) request).getDistribution().getStatus();
            row[3] = ((SendToSchoolRequest) request).getComments();
            model.addRow(row);
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btndistribution = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        receiveJTable = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnRefuse = new javax.swing.JButton();

        setBackground(new java.awt.Color(67, 80, 108));

        refreshTestJButton.setBackground(new java.awt.Color(61, 103, 155));
        refreshTestJButton.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(233, 233, 235));
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(233, 233, 235));
        valueLabel.setText("<value>");

        btndistribution.setBackground(new java.awt.Color(61, 103, 155));
        btndistribution.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btndistribution.setText("Distribution");
        btndistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndistributionActionPerformed(evt);
            }
        });

        receiveJTable.setBackground(new java.awt.Color(102, 102, 102));
        receiveJTable.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        receiveJTable.setForeground(new java.awt.Color(255, 255, 255));
        receiveJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Child Name", "Request Status", "Distribution status", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        receiveJTable.setRowHeight(20);
        receiveJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiveJTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(receiveJTable);

        btnAccept.setBackground(new java.awt.Color(61, 103, 155));
        btnAccept.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnRefuse.setBackground(new java.awt.Color(239, 75, 76));
        btnRefuse.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnRefuse.setText("Refuse");
        btnRefuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefuseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefuse, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndistribution, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                        .addComponent(refreshTestJButton))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefuse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndistribution, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void btndistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndistributionActionPerformed
        // TODO add your handling code here:
        Integer selectedRow = receiveJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row, no selected is not permitted");
            return;
        }
        SendToSchoolRequest chcrequest = (SendToSchoolRequest) receiveJTable.getValueAt(selectedRow, 0);

        if (chcrequest.getStatus().equals("Finished")) {
            JOptionPane.showMessageDialog(null, "This request has been finished now");
            return;
        }
        if (chcrequest.getStatus().equals("Refuse")) {
            JOptionPane.showMessageDialog(null, "This request has been Refused");
            return;
        }
        //chcrequest.childName();
        chcrequest.setStatus("Processing now");
        DistributionWorkAreaJPanel dwaJPanel = new DistributionWorkAreaJPanel(userProcessContainer, userAccount, enterprise, chcrequest, business);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DistributionWorkAreaJPanel", dwaJPanel);
        layout.next(userProcessContainer);
        dB4OUtil.storeSystem(business);

    }//GEN-LAST:event_btndistributionActionPerformed

    private void receiveJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiveJTableMouseClicked

    }//GEN-LAST:event_receiveJTableMouseClicked

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        Integer selectedRow = receiveJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row, no selected is not permitted");
            return;
        }
        SendToSchoolRequest chcrequest = (SendToSchoolRequest) receiveJTable.getValueAt(selectedRow, 0);
        chcrequest.setStatus("Pending");
        chcrequest.setChildStatus(true);
        dB4OUtil.storeSystem(business);

        populateRequestTable();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRefuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefuseActionPerformed
        // TODO add your handling code here:
        Integer selectedRow = receiveJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row, no selected is not permitted");
            return;
        }
        SendToSchoolRequest chcrequest = (SendToSchoolRequest) receiveJTable.getValueAt(selectedRow, 0);
        chcrequest.setStatus("Refuse");
        chcrequest.setChildStatus(false);
        populateRequestTable();
    }//GEN-LAST:event_btnRefuseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnRefuse;
    private javax.swing.JButton btndistribution;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable receiveJTable;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
