/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.GymRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.FitnessEnterprise;
import Business.Organization.Organization;
import Business.Organization.PTOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SendToFitnessRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dengy
 */
public class PTWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PTWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private FitnessEnterprise fitness;
    private UserAccount userAccount;
    private PTOrganization PTOrganization;
    private EcoSystem system;
    private String selection;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public PTWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, PTOrganization PTOrganization, FitnessEnterprise fitness) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.PTOrganization = PTOrganization;
        this.fitness = fitness;
        valueLabel.setText(fitness.getName());

        populateRequestTable();
        populateCombo();

    }

    private void populateCombo() {

        cmbPT.removeAllItems();

        cmbPT.addItem("Elliptical");
        cmbPT.addItem("Treadmill");
        cmbPT.addItem("Aerobic Traning");
        cmbPT.addItem("Stationary Bike");
        cmbPT.addItem("Bodybuilding");

        cmbPT.setSelectedIndex(-1);

    }

    private void populateRequestTable() {

        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);

        for (Organization o : fitness.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof PTOrganization) {
                for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                    for (WorkRequest wr : ua.getWorkQueue().getWorkRequestList()) {

                        SendToFitnessRequest sf = (SendToFitnessRequest) wr;
                        Object[] row = new Object[5];

                        row[0] = sf;
                        row[1] = sf.getChild().getName();
                        row[2] = sf.getChild().getGender();
                        row[3] = sf.getChild().getFitnessStatus();
                        row[4] = sf.getChild().getFitnessItem();
                        model.addRow(row);

                    }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        btnReceive = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        cmbPT = new javax.swing.JComboBox<>();
        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(67, 80, 108));
        setForeground(new java.awt.Color(102, 102, 102));

        valueLabel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(233, 233, 235));
        valueLabel.setText("<value>");

        btnReceive.setBackground(new java.awt.Color(61, 103, 155));
        btnReceive.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnReceive.setText("Accept");
        btnReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveActionPerformed(evt);
            }
        });

        workRequestJTable.setBackground(new java.awt.Color(102, 102, 102));
        workRequestJTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        workRequestJTable.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        workRequestJTable.setForeground(new java.awt.Color(255, 255, 255));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Status", "Fitness Item"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(20);
        workRequestJTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        workRequestJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workRequestJTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        btnAssign.setBackground(new java.awt.Color(61, 103, 155));
        btnAssign.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.setMaximumSize(new java.awt.Dimension(85, 29));
        btnAssign.setPreferredSize(new java.awt.Dimension(85, 29));
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        cmbPT.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        cmbPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPTActionPerformed(evt);
            }
        });

        refreshTestJButton.setBackground(new java.awt.Color(61, 103, 155));
        refreshTestJButton.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(233, 233, 235));
        enterpriseLabel.setText("EnterPrise :");

        btnReject.setBackground(new java.awt.Color(239, 75, 76));
        btnReject.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshTestJButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPT, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReceive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReject)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbPT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveActionPerformed

        Integer selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table");
            return;
        }

        SendToFitnessRequest sf = (SendToFitnessRequest) workRequestJTable.getValueAt(selectedRow, 0);

        if (sf.getChild().getFitnessStatus().equals("Enrolled")) {

            JOptionPane.showMessageDialog(null, "This Child is Already Enrolled!");
            return;

        } else {

            sf.getChild().setFitnessStatus("Enrolled");

        }

        populateRequestTable();

    }//GEN-LAST:event_btnReceiveActionPerformed

    private void workRequestJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workRequestJTableMouseClicked

    }//GEN-LAST:event_workRequestJTableMouseClicked

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed

        Integer selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table");
            return;
        }

        String fitnessItem = (String) cmbPT.getSelectedItem();
        if (fitnessItem == null) {
            JOptionPane.showMessageDialog(null, "Please select a PT Project!");
            return;
        }

        SendToFitnessRequest sf = (SendToFitnessRequest) workRequestJTable.getValueAt(selectedRow, 0);

        if (sf.getChild().getFitnessStatus().equals("Enrolled")) {

            sf.getChild().setFitnessItem(fitnessItem);

        } else {

            JOptionPane.showMessageDialog(null, "This Child Is Not Enrolled Yet!");
            return;

        }

        populateRequestTable();

    }//GEN-LAST:event_btnAssignActionPerformed

    private void cmbPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPTActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed

        Integer selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table");
            return;
        }

        SendToFitnessRequest sf = (SendToFitnessRequest) workRequestJTable.getValueAt(selectedRow, 0);

        if (sf.getChild().getFitnessStatus().equals("Rejected")) {

            JOptionPane.showMessageDialog(null, "This child is already Rejecte!");
            return;

        } else {

            sf.getChild().setFitnessStatus("Rejected");

        }

        populateRequestTable();

    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnReceive;
    private javax.swing.JButton btnReject;
    private javax.swing.JComboBox<String> cmbPT;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
