/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.ClothesRequest;
import Business.WorkQueue.DistributionWorkRequest;
import Business.WorkQueue.FoodRequest;
import Business.WorkQueue.SendToFitnessRequest;
import Business.WorkQueue.SendToSchoolRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author zhb970327
 */
public class AnalysisJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    /**
     * Creates new form AnalysisJPanel
     */
    public AnalysisJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnallforenterprise = new javax.swing.JButton();
        btntypeofrequest = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(250);

        jPanel1.setBackground(new java.awt.Color(67, 80, 108));

        btnallforenterprise.setBackground(new java.awt.Color(61, 103, 155));
        btnallforenterprise.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnallforenterprise.setText("All Enterprise Requests");
        btnallforenterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallforenterpriseActionPerformed(evt);
            }
        });

        btntypeofrequest.setBackground(new java.awt.Color(61, 103, 155));
        btntypeofrequest.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btntypeofrequest.setText("Type of Requests Count");
        btntypeofrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntypeofrequestActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnallforenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btntypeofrequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnback))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnallforenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btntypeofrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addComponent(btnback)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(67, 80, 108));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnallforenterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallforenterpriseActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dcdata = new DefaultCategoryDataset();
        int num;
                for (Network n : ecosystem.getNetworkList()) {
                    for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                        for(Organization org : e.getOrganizationDirectory().getOrganizationList()){
                                num=org.getWorkQueue().getWorkRequestList().size()+
                                (org.getUserAccountDirectory().getUserAccountList().stream()
                                        .mapToInt(uc->uc.getWorkQueue().getWorkRequestList().size()).sum());
                        dcdata.setValue(num, n.getName(), e.getName());
                        }
                    }
                }
                JFreeChart chart = ChartFactory.createBarChart3D("Each Enterprise's Requests", "Enterprise Name", "Requests number", dcdata, PlotOrientation.VERTICAL, false, true, false);
                ChartPanel CJPanel = new ChartPanel(chart);
                jSplitPane1.setBottomComponent(CJPanel);
    }//GEN-LAST:event_btnallforenterpriseActionPerformed

    private void btntypeofrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntypeofrequestActionPerformed
        // TODO add your handling code here:
        DefaultPieDataset dpdata = new DefaultPieDataset();
                int ClothesReq = 0;
                int DistributionWorkReq = 0;
                int FoodReq =0;
                int SendToFitnessReq = 0; 
                int SendToSchoolReq = 0;
                for (Network net : ecosystem.getNetworkList()) {
                    for (Enterprise ep : net.getEnterpriseDirectory().getEnterpriseList()) {
                        for(Organization org: ep.getOrganizationDirectory().getOrganizationList()){
                            for(WorkRequest w: org.getWorkQueue().getWorkRequestList()){
                            if(w instanceof ClothesRequest){
                                ClothesReq++;
                            }
                            else if(w instanceof DistributionWorkRequest){
                                DistributionWorkReq++;
                            }
                            else if(w instanceof FoodRequest){
                                FoodReq++;
                            }
                            else if (w instanceof SendToFitnessRequest){
                                SendToFitnessReq++;
                            }
                            else if (w instanceof SendToSchoolRequest){
                                SendToSchoolReq++;
                            }
                            }
                        }
                        for(Organization org: ep.getOrganizationDirectory().getOrganizationList()){
                          for(UserAccount ua: org.getUserAccountDirectory().getUserAccountList()){
                            for(WorkRequest w: ua.getWorkQueue().getWorkRequestList()){
                            if(w instanceof ClothesRequest){
                                ClothesReq++;
                            }
                            else if(w instanceof DistributionWorkRequest){
                                DistributionWorkReq++;
                            }
                            else if(w instanceof FoodRequest){
                                FoodReq++;
                            }
                            else if (w instanceof SendToFitnessRequest){
                                SendToFitnessReq++;
                            }
                            else if (w instanceof SendToSchoolRequest){
                                SendToSchoolReq++;
                            }
                            }
                        }
                        }
                    }
                }
                dpdata.setValue("Clothes Request", new Integer(ClothesReq));
                dpdata.setValue("DistributionWork Request", new Integer(DistributionWorkReq));
                dpdata.setValue("Food Request", new Integer(FoodReq));
                dpdata.setValue("SendToFitness Request", new Integer(SendToFitnessReq));
                dpdata.setValue("SendToSchool Request", new Integer(SendToSchoolReq));
                JFreeChart jChart = ChartFactory.createPieChart("Request quantity statistics chart", dpdata, true, true, true);
                ChartPanel CJPanel = new ChartPanel(jChart);
                jSplitPane1.setBottomComponent(CJPanel);
    }//GEN-LAST:event_btntypeofrequestActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnallforenterprise;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btntypeofrequest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
